### ISSUE TITLE
Сделать страницу регистрации пользователя

### ISSUE THREAD

**Issue by ufadeeva** [OnBrains/WorkAssistant#14]
На форме логирования добавить кнопку регистрации нового пользователя, со всем вытекающими последствиями, т.е. переходом на форму регистрации.

**Comment by ufadeeva** [comment]
Замечание 1.
Не работает проверка пароля.
При вводе пароля повторно при регистрации, не проверяется, совпадаю ли введенные пароли.

**Comment by HAYMbl4** [comment]
Добавил проверку пароля.
