### ISSUE TITLE
Доработки GUI

### ISSUE THREAD

**Issue by ufadeeva** [OnBrains/WorkAssistant#9]
# Замечания-пожелания-пояснения к UI.
1. *  кнопка плей - начало раб.дня.
  * стоп - окончание.
  * пауза - отлучение
  * пауза-плей - вернуться из отлучения.

2. При нажатии на плей, включается таймер, с отображением оставшегося времени.
Таймер ведет обратный отсчет. При перехождении нуля, цифры таймера меняют цвет (например, становятся зелеными), и идет отсчет переработанного времени.. уже не обратный.

3. В табличке, при редактировании времени не нужно открывать целый календарь. Зачем? Ты же при редактировании и так встаешь на строчку определенного дня. Нужно добавить возможность редактирования только времени.

## Макет, версия 1.
![ui_ver_1 0 0](https://cloud.githubusercontent.com/assets/6511898/7107251/7432f8bc-e168-11e4-88e0-ed64198889e4.png)

**Comment by ufadeeva** [comment]
https://drive.google.com/file/d/0B4tvka5AyMBRYnpwZ1M2U3NpbVk/view?usp=sharing
Новый макет.

**Comment by ufadeeva** [comment]
https://drive.google.com/file/d/0B4tvka5AyMBRMVYzblZMNXVWU3c/view?usp=sharing

Добавила верхнюю панель, для будущего меню.
Добавила пример фона.

На календаре можно сделать возможность отмечать отпуск, отгулы, больничные и т.д.
Как в Жире сейчас  - можно на календаре создавать события.

**Comment by HAYMbl4** [comment]
Немного поправил UI, то что сейчас есть:

## Главная форма
![maim_view](https://cloud.githubusercontent.com/assets/6511898/7107238/de541ad8-e167-11e4-90c3-38b9762f02b1.png)

## Редактирование рабочего дня
![edit_time](https://cloud.githubusercontent.com/assets/6511898/7107241/102af8c4-e168-11e4-84bb-31d1bc96b92a.png)

## Редактирование состояния
![edit_state](https://cloud.githubusercontent.com/assets/6511898/7107243/26bf1d90-e168-11e4-926c-bc7508b11ef2.png)
